routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'auth'],function(){
    Route::get('/','AdminController@index')->name('index');
    Route::get('/add-floor','AdminController@AddFloor')->name('add.floor');
    Route::post('/save-floor','AdminController@storeFloor')->name('store.floor');
    Route::get('/settings','AdminController@Settings')->name('settings');
    Route::post('/settings/save','AdminController@UpdateSettings')->name('settings.save');

    Route::get('/add-layouts-details','AdminController@AddLayOutDetails')->name('add.layout.details');
    Route::post('/save-layouts-detail','AdminController@SaveLayoutDetails')->name('save.layout.details');

    Route::get('/layouts-list','AdminController@LayOutsList')->name('layouts.list');
    Route::get('edit-layout/{id}','AdminController@EditLayout')->name('layouts.edit');
    Route::post('/update-layout','AdminController@UpdateLayoutDetail')->name('update.layout.details');
    // Admin Translations
    Route::get('/translation','AdminController@translation')->name('translation');
    Route::post('/translation/add','AdminController@translationAdd')->name('translation.add');
    Route::get('/translation/delete/{id}','AdminController@translationDelete')->name('translation.delete');
    Route::post('/translation/edit','AdminController@translationEdit')->name('translation.edit');
    Route::get('/video','AdminController@Video')->name('video');

//    Admin Settings
    Route::post('/save-video','AdminController@saveVideo')->name('save-video');

//    Gallery
    Route::get('/photo-gallery','AdminController@PhotoGalleryIndex')->name('photo-gallery-index');
    Route::post('/photo-gallery/save','AdminController@PhotoGallerySave')->name('photo-gallery-save');
    Route::get('/photo-gallery/delete/{id}','AdminController@PhotoGalleryDelete')->name('gallery-delete');
    Route::post('/photo-gallery/changeOrder','AdminController@PhotoGalleryChangeOrder')->name('gallery-change-order');


    //    Gallery
    Route::get('/partners-gallery','AdminController@PartnersIndex')->name('partners-index');
    Route::post('/partners-gallery/save','AdminController@PartnersSave')->name('partners-save');
    Route::get('/partners-gallery/delete/{id}','AdminController@PartnersDelete')->name('partners-delete');
    Route::post('/partners-gallery/changeOrder','AdminController@PartnersChangeOrder')->name('partners-change-order');

    // aboutus
    Route::get('/about-us','AdminController@AboutUs')->name('about.us');
    Route::post('/about-us/store','AdminController@AboutUsUpdate')->name('about.store');

    Route::get('about-us-icons','AdminController@AboutUsIcons')->name('about.us.icons');
    Route::get('add-about-icon','AdminController@AddAboutUsIcon')->name('about.us.icons.add');
    Route::post('save-about-icon','AdminController@SaveAboutIcon')->name('save.about.icons');
    Route::get('/edit-about-icon/{id}','AdminController@EditAboutIcon')->name('edit.about.icon');
    Route::post('/update-about-icon/{id}','AdminController@UpdateAboutIcon')->name('update.about.icon');
    Route::get('/delete-about-us-icon/{id}','AdminController@DeleteAboutUsIcon')->name('delete.about.us.icon');
});

Route::group(['prefix' => '{locale?}','middleware' => 'locale'], function () {
    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/home', 'HomeController@index')->name('home');
});

resources/views/admin/floor/add.blade.php
@extends('_layouts.admin')
@section('content')
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (count($errors) > 0)


                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach

                    </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">

                            {!! \Session::get('success') !!}

                        </div>
                    @endif
                    <div class="card-header">
                        <h3 class="card-title">Add floor
                        </h3>
                        <div class="d-flex justify-content-end">

                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">


                        <div class="row">
                            <div class="col-xl-12 mb-4 mb-xl-0">
                                <section>
                                    <form action="{{route('admin.store.floor')}}" method="POST" enctype="multipart/form-data">
                                        @csrf

                                        <div class="tab-content" id="myTabContent">

                                            <div class="tab-pane fade active show" id="home" role="tabpanel" aria-labelledby="home-tab">
                                                <div class="card card-primary">


                                                    <div class="card-body">

                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Name</label>
                                                                <input type="text" name="name" class="form-control">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Floor</label>
                                                                <input type="number" name="floor" class="form-control">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Start</label>
                                                                <input type="text" name="start" class="form-control">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">End</label>
                                                                <input type="text" name="end" class="form-control">
                                                            </div>
                                                        </div>

                                                    </div>


                                                </div>
                                            </div>

                                            <div class="form-group form_flex">
                                                <p>Image</p>
                                                <input type='file' id="image" name="image"/>
                                                <img id="img" style="width: 200px; display: none" src="" alt="your image"/>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-success">Add</button>
                                    </form>
                                </section>
                                <!-- Section: Live preview -->

                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.modal -->
@endsection

@section('script')
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#img').attr('src', e.target.result);
                $('#img').show();
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }
    $("#image").change(function() {
        readURL(this);
    });
</script>
@endsection

resources/views/admin/floor/addFloorDetails.blade.php
@extends('_layouts.admin')
@section('content')
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (count($errors) > 0)


                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach

                    </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">

                            {!! \Session::get('success') !!}

                        </div>
                    @endif
                    <div class="card-header">
                        <h3 class="card-title">Add floor
                        </h3>
                        <div class="d-flex justify-content-end">

                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">


                        <div class="row">
                            <div class="col-xl-12 mb-4 mb-xl-0">
                                <section>
                                    <form action="{{route('admin.save.layout.details')}}" method="POST"
                                          enctype="multipart/form-data">
                                        @csrf

                                        <div class="tab-content" id="myTabContent">

                                            <div class="tab-pane fade active show" id="home" role="tabpanel"
                                                 aria-labelledby="home-tab">
                                                <div class="card card-primary">


                                                    <div class="card-body">

                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="parent_id">Parent</label>
                                                                <select name="parent_id" class="form-control"
                                                                        id="parent_id">
                                                                    @foreach($floors as $floor)
                                                                        <option
                                                                            value="{{$floor->id}}" {{$floor->id==4?'selected':""}}>{{$floor->floor}}</option>
                                                                    @endforeach
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="layoutDetails">
                                                            <button class="btn btn-success adddetail" type="button"><i
                                                                    class="fa fa-plus"></i></button>
                                                            <div class="form-group">
                                                                <div class="mb-3">
                                                                    <label for="detail">Detail</label>
                                                                    <textarea name="details[]"
                                                                              class="form-control"></textarea>
                                                                </div>
                                                            </div>
                                                        </div>


                                                    </div>


                                                </div>
                                            </div>


                                        </div>
                                        <button type="submit" class="btn btn-success">Add</button>
                                    </form>
                                </section>
                                <!-- Section: Live preview -->

                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.modal -->
@endsection

@section('script')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img').attr('src', e.target.result);
                    $('#img').show();
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }

        $("#image").change(function () {
            readURL(this);
        });

        $('.adddetail').click(function (e) {
            var append = `<div class="form-group appended">
                                                            <div class="mb-3">
                                                                <label for="detail">Detail <button type="button" class="btn btn-danger removedetails"><i class="fa fa-minus"></i></button></label>
                                                                <textarea name="details[]" class="form-control"></textarea>
                                                            </div>
                                                        </div>`;
            $('.layoutDetails').append(append)
        });

        $(document).on('click','.removedetails',function (){
            $(this).closest('.appended').remove();
        })
    </script>
@endsection

resources/views/admin/floor/layoutEdit.blade.php
@extends('_layouts.admin')
@section('content')
    <style>
    .form-check{
        padding-right: 10px;
    }
    </style>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (count($errors) > 0)


                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach

                    </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">

                            {!! \Session::get('success') !!}

                        </div>
                    @endif
                    <div class="card-header">
                        <h3 class="card-title">Edit floor details</h3>
                        <div class="d-flex justify-content-end">

                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">


                        <div class="row">
                            <div class="col-md-12">
                                <section>
                                    <form action="{{route('admin.store.floor')}}" method="POST"
                                          enctype="multipart/form-data">
                                        @csrf
                                        <div class="floor-list" style="width: 800px">

                                        <img id="vegetables" style="width: 800px; max-width: 800px" src="{{asset('uploads/'.$layout->image)}}"
                                                 usemap="#veg"/>

                                            <map id="veg_map" name="veg">
                                                @if($layout->details->count()>0)
                                                    @foreach($layout->details as $detail)
                                                        @php
                                                            $d = $detail->detail;

                                                            $rand = str_random(9);
                                                            $d = str_replace('name=""',"name='$rand'",$d);
                                                           $d = str_replace('data-bussy=""',"data-bussy='$detail->busy' data-ids='$detail->id' data-image='".asset('uploads/'.$detail->image)."'",$d);
                                                        @endphp
                                                        {!! $d !!}
                                                    @endforeach
                                                @endif
                                            </map>
                                        </div>
                                        <button type="submit" class="btn btn-success">Add</button>
                                    </form>
                                </section>
                                <!-- Section: Live preview -->

                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <div class="modal fade bd-example-modal-lg showModalDetails" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <form action="{{route('admin.update.layout.details')}}" method="post"  enctype="multipart/form-data">
                            @csrf
                            <input type="hidden" name="id">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Edit flool detail</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <div class="row mb-0">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="busy"  value="yes" id="busyYes">
                                        <label class="form-check-label" for="flexRadioDefault1">
                                           Yes
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="busy" value="no" id="busyNo" checked>
                                        <label class="form-check-label" for="flexRadioDefault2">
                                            No
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <img src="" id="layoutdetailimage" class="img-fluid">

                            <div class="form-group" style="margin: 10px">
                                <input type="file" name="image" id="image">
                                <div>
                                    <img src="" id="img" style="display: none; width: 100%" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!-- /.modal -->
@endsection

@section('script')
    <script src="https://cdn.jsdelivr.net/npm/imagemapster@1.5.4/dist/jquery.imagemapster.js"></script>
    <script>


        let image = $('#vegetables');
        var areas = [];
        $('map').find('area').each(function () {
            var color = "33ff00b8";
            if ($(this).data('bussy') == 'yes') {
                color = 'ff0000c7'
            }
            areas.push({
                key: $(this).attr('name'),
                fillColor: color
            })
        })
        image.mapster(
            {

                fillOpacity: 0.8,
                fillColor: "ef280b",
                stroke: true,
                strokeColor: "3320FF",
                strokeOpacity: 0.8,
                strokeWidth: 0.2,
                singleSelect: true,
                mapKey: 'name',
                listKey: 'name',
                toolTipClose: ["tooltip-click", "area-click"],
                areas: areas
            });

        $('map area').click(function (e){
            e.preventDefault()
        $('.showModalDetails').modal('show')
            $('#layoutdetailimage').attr('src',$(this).data('image'));
            $('input[name=id]').val($(this).data('ids'));
            var busy = $(this).data('bussy');
            if(busy=='yes'){
                $('#busyYes').prop('checked',true)
                $('#busyNo').prop('checked',false)

            }else if(busy=='no'){
                $('#busyYes').prop('checked',false)
                $('#busyNo').prop('checked',true)


            }

        })


    </script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img').attr('src', e.target.result);
                    $('#img').show();
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }

        $("#image").change(function () {
            readURL(this);

        });
    </script>
@endsection

resources/views/admin/floor/list.blade.php
@extends('_layouts.admin')
@section('content')
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (count($errors) > 0)


                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach

                    </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">

                            {!! \Session::get('success') !!}

                        </div>
                    @endif
                    <div class="card-header">
                        <h3 class="card-title">Layouts list</h3>
                        <div class="d-flex justify-content-end">

                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Floor</th>
                                <th>Layout</th>


                                <th>*</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($layouts as $key => $layout)
                                @if(!empty($layout->details))
                                    <tr>

                                        <td>{{$layout->floor}}</td>
                                        <td>
                                            <img width="300px" src="{{asset('uploads/'.$layout->image)}}" alt="">
                                        </td>

                                        <td>

                                            <a href="{{route('admin.layouts.edit',$layout->id)}}" class="btn btn-warning">
                                                <i class="fas fa-edit"></i> Edit
                                            </a>
                                        </td>
                                    </tr>
                                @endif
                            @endforeach
                            </tbody>

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
        </div>

    </section>
    <!-- /.modal -->
@endsection