routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'auth'],function(){
    Route::get('/','AdminController@index')->name('index');
    Route::get('/add-floor','AdminController@AddFloor')->name('add.floor');
    Route::post('/save-floor','AdminController@storeFloor')->name('store.floor');
    Route::get('/settings','AdminController@Settings')->name('settings');
    Route::post('/settings/save','AdminController@UpdateSettings')->name('settings.save');

    Route::get('/add-layouts-details','AdminController@AddLayOutDetails')->name('add.layout.details');
    Route::post('/save-layouts-detail','AdminController@SaveLayoutDetails')->name('save.layout.details');

    Route::get('/layouts-list','AdminController@LayOutsList')->name('layouts.list');
    Route::get('edit-layout/{id}','AdminController@EditLayout')->name('layouts.edit');
    Route::post('/update-layout','AdminController@UpdateLayoutDetail')->name('update.layout.details');
    // Admin Translations
    Route::get('/translation','AdminController@translation')->name('translation');
    Route::post('/translation/add','AdminController@translationAdd')->name('translation.add');
    Route::get('/translation/delete/{id}','AdminController@translationDelete')->name('translation.delete');
    Route::post('/translation/edit','AdminController@translationEdit')->name('translation.edit');
    Route::get('/video','AdminController@Video')->name('video');

//    Admin Settings
    Route::post('/save-video','AdminController@saveVideo')->name('save-video');

//    Gallery
    Route::get('/photo-gallery','AdminController@PhotoGalleryIndex')->name('photo-gallery-index');
    Route::post('/photo-gallery/save','AdminController@PhotoGallerySave')->name('photo-gallery-save');
    Route::get('/photo-gallery/delete/{id}','AdminController@PhotoGalleryDelete')->name('gallery-delete');
    Route::post('/photo-gallery/changeOrder','AdminController@PhotoGalleryChangeOrder')->name('gallery-change-order');


    //    Gallery
    Route::get('/partners-gallery','AdminController@PartnersIndex')->name('partners-index');
    Route::post('/partners-gallery/save','AdminController@PartnersSave')->name('partners-save');
    Route::get('/partners-gallery/delete/{id}','AdminController@PartnersDelete')->name('partners-delete');
    Route::post('/partners-gallery/changeOrder','AdminController@PartnersChangeOrder')->name('partners-change-order');

    // aboutus
    Route::get('/about-us','AdminController@AboutUs')->name('about.us');
    Route::post('/about-us/store','AdminController@AboutUsUpdate')->name('about.store');

    Route::get('about-us-icons','AdminController@AboutUsIcons')->name('about.us.icons');
    Route::get('add-about-icon','AdminController@AddAboutUsIcon')->name('about.us.icons.add');
    Route::post('save-about-icon','AdminController@SaveAboutIcon')->name('save.about.icons');
    Route::get('/edit-about-icon/{id}','AdminController@EditAboutIcon')->name('edit.about.icon');
    Route::post('/update-about-icon/{id}','AdminController@UpdateAboutIcon')->name('update.about.icon');
    Route::get('/delete-about-us-icon/{id}','AdminController@DeleteAboutUsIcon')->name('delete.about.us.icon');
});

Route::group(['prefix' => '{locale?}','middleware' => 'locale'], function () {
    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/home', 'HomeController@index')->name('home');
});

resources/views/admin/aboutIcons.blade.php
@extends('_layouts.admin')
@section('content')

    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (count($errors) > 0)


                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach

                    </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">

                            {!! \Session::get('success') !!}

                        </div>
                    @endif
                    <div class="card-header">
                        <h3 class="card-title">About icons</h3>
                        <div class="d-flex justify-content-end">
                            <a class="btn btn-success" href="{{route('admin.about.us.icons.add')}}">Add Icon</a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Icon</th>
                                <th>Text</th>
                                <th>*</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($icons as $key => $icon)
                                    <tr>

                                        <td>
                                            <i style="font-size: 37px;color:green" class="{{$icon->icon}}"></i>
                                        </td>
                                        <td>
                                            {{$icon->text}}
                                        </td>

                                        <td>

                                            <a href="{{route('admin.edit.about.icon',$icon->unique_id)}}" class="btn btn-warning">
                                                <i class="fas fa-edit"></i> Edit
                                            </a>

                                            <a href="{{route('admin.delete.about.us.icon',$icon->unique_id)}}" class="btn btn-danger">
                                                <i class="fas fa-trash"></i> Delete
                                            </a>
                                        </td>
                                    </tr>
                            @endforeach
                            </tbody>

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
        </div>

    </section>
    <!-- /.modal -->
@endsection

resources/views/admin/addAboutIcon.blade.php
@extends('_layouts.admin')
@section('content')
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (count($errors) > 0)


                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach

                    </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">

                            {!! \Session::get('success') !!}

                        </div>
                    @endif
                    <div class="card-header">
                        <h3 class="card-title">Add Icon
                        </h3>
                        <div class="d-flex justify-content-end">

                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">


                        <div class="row">
                            <div class="col-xl-12 mb-4 mb-xl-0">
                                <section>
                                    <form action="{{route('admin.save.about.icons')}}" method="POST" enctype="multipart/form-data">
                                        @csrf

                                        <div class="tab-content" id="myTabContent">

                                            <div class="tab-pane fade active show" id="home" role="tabpanel" aria-labelledby="home-tab">
                                                <div class="card card-primary">


                                                    <div class="card-body">

                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Icon</label>
                                                                <input type="text" name="icon" class="form-control">
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Text Armenian</label>
                                                                <input type="text" name="text_am" class="form-control">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Text English</label>
                                                                <input type="text" name="text_en" class="form-control">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Text Russian</label>
                                                                <input type="text" name="text_ru" class="form-control">
                                                            </div>
                                                        </div>

                                                    </div>


                                                </div>
                                            </div>

                                        </div>
                                        <button type="submit" class="btn btn-success">Add</button>
                                    </form>
                                </section>
                                <!-- Section: Live preview -->

                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.modal -->
@endsection

@section('script')
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#img').attr('src', e.target.result);
                $('#img').show();
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }
    $("#image").change(function() {
        readURL(this);
    });
</script>
@endsection

resources/views/admin/editAboutIcon.blade.php
@extends('_layouts.admin')
@section('content')
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (count($errors) > 0)


                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach

                    </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">

                            {!! \Session::get('success') !!}

                        </div>
                    @endif
                    <div class="card-header">
                        <h3 class="card-title">Edit Icon
                        </h3>
                        <div class="d-flex justify-content-end">

                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">


                        <div class="row">
                            <div class="col-xl-12 mb-4 mb-xl-0">
                                <section>
                                    <form action="{{route('admin.update.about.icon',$icon_am->unique_id)}}" method="POST" enctype="multipart/form-data">
                                        @csrf

                                        <div class="tab-content" id="myTabContent">

                                            <div class="tab-pane fade active show" id="home" role="tabpanel" aria-labelledby="home-tab">
                                                <div class="card card-primary">


                                                    <div class="card-body">

                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Icon</label>
                                                                <input type="text" name="icon" value="{{$icon_am->icon}}" class="form-control">
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Text Armenian</label>
                                                                <input type="text" value="{{$icon_am->text}}" name="text_am" class="form-control">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Text English</label>
                                                                <input type="text" value="{{$icon_en->text}}"  name="text_en" class="form-control">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="mb-3">
                                                                <label for="desc_am">Text Russian</label>
                                                                <input type="text" value="{{$icon_ru->text}}"  name="text_ru" class="form-control">
                                                            </div>
                                                        </div>

                                                    </div>


                                                </div>
                                            </div>

                                        </div>
                                        <button type="submit" class="btn btn-success">Add</button>
                                    </form>
                                </section>
                                <!-- Section: Live preview -->

                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.modal -->
@endsection

@section('script')
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#img').attr('src', e.target.result);
                $('#img').show();
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }
    $("#image").change(function() {
        readURL(this);
    });
</script>
@endsection

resources/views/admin/translation.blade.php
@extends('_layouts.admin')
@section('content')
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (count($errors) > 0)


                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach

                    </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">

                            {!! \Session::get('success') !!}

                        </div>
                    @endif
                    <div class="card-header">
                        <h3 class="card-title">String Translation</h3>
                        <div class="d-flex justify-content-end">
                            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">
                                Add Translation
                            </button>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Key</th>
                                <th>Am</th>
                                <th>Ru</th>
                                <th>En</th>
                                <th>*</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($translation as $trans)
                                <tr>

                                    <td>{{$trans->id}}</td>
                                    <td>{{$trans->key}}</td>
                                    <td>{{$trans->am}}</td>
                                    <td>{{$trans->ru}}</td>
                                    <td>{{$trans->en}}</td>
                                    <td>
                                        <button data-id="{{$trans->id}}" data-key="{{$trans->key}}" data-am="{{$trans->am}}" data-ru="{{$trans->ru}}" data-en="{{$trans->en}}" type="button" class="btn btn-info edites" data-toggle="modal" data-target="#modal-edit">
                                            <i class="fas fa-edit"></i> Խմբագրել
                                        </button>

                                        <a href="{{route('admin.translation.delete',$trans->id)}}" class="btn btn-danger" onclick="return confirm('Are you sure?')">
                                            <i class="fas fa-trash-alt"></i> Ջնջել
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
        </div>

    </section>
    <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Translation</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form role="form" method="POST" action="{{route('admin.translation.add')}}">
                    @csrf
                    <div class="modal-body">
                        <div class="card card-primary">

                            <!-- /.card-header -->
                            <!-- form start -->

                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Key</label>
                                    <input type="text" name="key" class="form-control" id="exampleInputEmail1" placeholder="Enter Key">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Am</label>
                                    <input type="text" name="am" class="form-control" id="exampleInputPassword1" placeholder="Enter translation Armenian">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Ru</label>
                                    <input type="text" name="ru" class="form-control" id="exampleInputPassword1" placeholder="Enter translation Russian">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">En</label>
                                    <input type="text" name="en" class="form-control" id="exampleInputPassword1" placeholder="Enter translation English">
                                </div>

                            </div>


                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->


    <div class="modal fade" id="modal-edit">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Edit Translation</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form role="form" method="POST" action="{{route('admin.translation.edit')}}">
                    @csrf
                    <input type="hidden" name="editid" id="editid">
                    <div class="modal-body">
                        <div class="card card-primary">

                            <!-- /.card-header -->
                            <!-- form start -->

                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Key</label>
                                    <input type="text" name="key" class="form-control" id="editkey" placeholder="Enter Key">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Am</label>
                                    <input type="text" name="am" class="form-control" id="editam" placeholder="Enter translation Armenian">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Ru</label>
                                    <input type="text" name="ru" class="form-control" id="editru" placeholder="Enter translation Russian">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">En</label>
                                    <input type="text" name="en" class="form-control" id="editen" placeholder="Enter translation English">
                                </div>

                            </div>


                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@endsection
@section('script')
    <script>
        $('.edites').click(function (e){
            let id = $(this).data('id');
            let key = $(this).data('key');
            let am = $(this).data('am');
            let en = $(this).data('en');
            let ru = $(this).data('ru');

            $('#editkey').val(key);
            $('#editam').val(am);
            $('#editru').val(ru);
            $('#editen').val(en);
            $('#editid').val(id);

        })
    </script>
@endsection

resources/views/admin/video.blade.php
@extends('_layouts.admin')
@section('content')
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                            @if (\Session::has('success'))
                                <div class="alert alert-success">
                                    <ul>
                                        <li>{!! \Session::get('success') !!}</li>
                                    </ul>
                                </div>
                            @endif
                            @if ($video)
                                <div class="card text-center">
                                    <div class="card-header">
                                        Main page video already exists. If You want to change it, upload new one.str_random
                                    </div>
                                    <div class="card-body">
                                        <video style="width: 100%" src="{{$video->value}}" controls></video>
                                    </div>
                                </div>
                            @endif
                            <div class="card text-center">
                                <div class="card-header">
                                    Main Page Video
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">Add or Edit main page video</h5>
                                    <p class="card-text"></p>
                                    <form action="{{route('admin.save-video')}}" enctype="multipart/form-data" method="POST">
                                        @csrf

                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="video" id="validatedCustomFile"  accept="video/*" required>
                                            <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                                            <div class="invalid-feedback">Example invalid custom file feedback</div>
                                        </div>
                                        <div class="mt-5">
                                            <button class="btn btn-success">Save Video</button>
                                        </div>
                                    </form>

                                </div>

                            </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection